---
- name: 4.7.1.6 Rollback CDE remote GUI login
  hosts: all
  become: yes
  gather_facts: no

  vars:
    pre_check_file: "/tmp/pre_checks/4.7.1.6_pre_checks.{{ ansible_hostname }}.txt"

  tasks:
    - name: Read pre-check file content from Ansible host
      ansible.builtin.slurp:
        src: "{{ pre_check_file }}"
      delegate_to: localhost
      register: pre_check_content
      ignore_errors: yes

    - name: Fail if pre-check file was not found
      ansible.builtin.fail:
        msg: "The pre-check file was not found on the Ansible host. Cannot perform rollback."
      when: not pre_check_content.content is defined

    - name: Restore Xaccess file to its original state
      ansible.builtin.copy:
        content: "{{ pre_check_content.content | b64decode }}"
        dest: /etc/dt/config/Xaccess
        owner: root
        group: sys
        mode: '0644'
      when: pre_check_content.content is defined
      