  tasks:
    - name: 4.1.1.4 Get current permissions of /etc/inetd.conf
      ansible.builtin.stat:
        path: /etc/inetd.conf
      register: inetd_conf_stat

    - name: Get current trust status of /etc/inetd.conf
      ansible.builtin.command: trustchk /etc/inetd.conf
      register: trustchk_status
      ignore_errors: true
      
    - name: Save settings to a local rollback file
      ansible.builtin.copy:
        content: |
          # Rollback information for {{ inventory_hostname }}
          # Task: 4.1.1.3
          path: /etc/inetd.conf
          owner: {{ inetd_conf_stat.stat.pw_name }}
          group: {{ inetd_conf_stat.stat.gr_name }}
          mode: '{{ inetd_conf_stat.stat.mode }}'
          trust_status: {{ trustchk_status.stdout | default('N/A') }}
        dest: "/tmp/4.1.1.3_etc_inetd.conf_rollback_{{ inventory_hostname }}.txt"
      delegate_to: localhost