    - name: 4.1.1.3 Get current settings for /etc/inetd.conf
      ansible.builtin.stat:
        path: /etc/inetd.conf
      register: inetd_conf_stat

    - name: Save settings to a local rollback file (4.1.1.3)
      ansible.builtin.copy:
        content: |
          # Rollback information for {{ inventory_hostname }}
          # Task: 4.1.1.3
          path: /etc/inetd.conf
          owner: {{ inetd_conf_stat.stat.pw_name }}
          group: {{ inetd_conf_stat.stat.gr_name }}
          mode: '{{ inetd_conf_stat.stat.mode }}'
        dest: "/tmp/4.1.1.3_etc_inetd.conf_rollback_{{ inventory_hostname }}.txt"
      delegate_to: localhost