- name: 4.7.1.8 Pre-check CDE login screen hostname status
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Create pre_checks directory on Ansible host
      ansible.builtin.file:
        path: "/tmp/pre_checks"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: yes

    - name: Read the content of the Xconfig file
      ansible.builtin.slurp:
        src: /etc/dt/config/Xconfig
      register: xconfig_content
      when: ansible_os_family == 'AIX'
      ignore_errors: yes

    - name: Write the file content to a file on the Ansible host
      ansible.builtin.copy:
        content: "{{ xconfig_content.content | b64decode | default('File not found') }}"
        dest: "/tmp/pre_checks/4.7.1.8_pre_checks.{{ ansible_hostname }}.txt"
      delegate_to: localhost
      when: xconfig_content.content is defined
