- name: 4.7.2 Pre-check FTP Daemon Configuration
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Create pre_checks directory on Ansible host
      ansible.builtin.file:
        path: "/tmp/pre_checks"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: yes

    - name: Backup /etc/ftpusers
      ansible.builtin.copy:
        src: /etc/ftpusers
        dest: "/tmp/pre_checks/4.7.2_ftpusers_pre_check.{{ ansible_hostname }}.txt"
        mode: '0644'
        remote_src: yes
      delegate_to: localhost
      ignore_errors: yes

    - name: Backup /etc/ftpaccess
      ansible.builtin.copy:
        src: /etc/ftpaccess
        dest: "/tmp/pre_checks/4.7.2_ftpaccess_pre_check.{{ ansible_hostname }}.txt"
        mode: '0644'
        remote_src: yes
      delegate_to: localhost
      ignore_errors: yes
