    - name: 4.1.1.1 Read the rollback file from the local machine
      ansible.builtin.slurp:
        src: "/tmp/smit_log_rollback_{{ inventory_hostname }}.txt"
      register: rollback_file_content
      delegate_to: localhost
      
    - name: Set permissions, owner, and group on /smit.log
      ansible.builtin.file:
        path: /smit.log
        owner: "{{ (rollback_file_content.content | b64decode | from_yaml).owner }}"
        group: "{{ (rollback_file_content.content | b64decode | from_yaml).group }}"
        mode: "{{ (rollback_file_content.content | b64decode | from_yaml).mode }}"