---
- name: 4.4.3.1 Pre-check device permissions
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Create pre_checks directory on Ansible host
      ansible.builtin.file:
        path: "/tmp/pre_checks"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: yes

    - name: Backup /etc/security/devpermit file
      ansible.builtin.copy:
        src: /etc/security/devpermit
        dest: "/tmp/pre_checks/4.4.3.1_pre_check.{{ ansible_hostname }}.txt"
        mode: '0644'
        remote_src: yes
      delegate_to: localhost
      ignore_errors: yes
