    - name: Create pre_checks directory on Ansible host
      ansible.builtin.file:
        path: /tmp/pre_checks
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: check if  /usr/dt/bin/ exists
      ansible.builtin.stat:
        path: /usr/dt/bin/
      register: dt_bin_stat


    - name: Get file attributes of CDE daemons
      ansible.builtin.stat:
        path: "{{ item }}"
      with_items: "{{ cde_daemons }}"
      ignore_errors: yes
      register: cde_daemon_stats
      when: dt_bin_stat.stat.exists and dt_bin_stat.stat.isdir

    - name: Write sgid and suid status to a file on the Ansible host
      ansible.builtin.copy:
        content: |
          ---
          CDE Daemons sgid/suid Pre-check for {{ ansible_hostname }}

          {% for daemon in cde_daemon_stats.results %}
          {# Use daemon.stat | default({}) to safely access attributes even if the stat check failed/skipped #}
          {% set s = daemon.stat | default({}) %}

          --- Path: {{ s.path | default('Not found') }} ---
          Permissions: {{ s.mode | default('N/A') }}
          Is setuid enabled: {{ 'yes' if s.isuid | default(false) else 'no' }}
          Is setgid enabled: {{ 'yes' if s.isgid | default(false) else 'no' }}

          {% endfor %}
        dest: "/tmp/pre_checks/4.7.1.5_pre_checks.{{ ansible_hostname }}.txt"
      delegate_to: localhost
      when: dt_bin_stat.stat.exists and dt_bin_stat.stat.isdir
