---
- name: Rollback CDE service status to pre-check state
  hosts: all
  become: yes
  gather_facts: no

  vars:
    pre_check_file: "/tmp/pre_checks/4.7.1.2-4.{{ ansible_hostname }}.txt"

  tasks:
    - name: Fetch pre-check status file from remote host
      ansible.builtin.fetch:
        src: "{{ pre_check_file }}"
        dest: "/tmp/pre_check_rollback_data/"
        flat: yes
      delegate_to: "{{ inventory_hostname }}"
      register: fetched_file

    - name: Read content of the fetched file
      ansible.builtin.slurp:
        src: "{{ fetched_file.dest }}"
      delegate_to: localhost
      register: file_content

    - name: Set facts for original service states
      ansible.builtin.set_fact:
        cmsd_was_running: "{{ 'Active' in (file_content.content | b64decode) }}"
        dtlogin_was_running: "{{ 'Active' in (file_content.content | b64decode) }}"
        dtspc_was_running: "{{ 'Active' in (file_content.content | b64decode) }}"

    - name: 4.7.1.2 Rollback cmsd service
      ansible.builtin.service:
        name: cmsd
        state: started
        enabled: yes
      when: cmsd_was_running

    - name: 4.7.1.3 Rollback dtlogin service
      ansible.builtin.service:
        name: dtlogin
        state: started
        enabled: yes
      when: dtlogin_was_running

    - name: 4.7.1.4 Rollback dtspc service
      ansible.builtin.service:
        name: dtspc
        state: started
        enabled: yes
      when: dtspc_was_running