---
- name: 5.3 Pre-check system users security
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Create pre_checks directory on Ansible host
      ansible.builtin.file:
        path: "/tmp/pre_checks"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: yes

    - name: Get current user information
      ansible.builtin.shell: |
        /usr/sbin/lsuser -a id home shell account_locked {{ item }}
      loop:
        - bin
        - daemon
        - guest
        - lpd
        - nobody
        - nuucp
        - sys
        - uucp
      register: user_info_results
      changed_when: false
      failed_when: false

    - name: Write user info to a file on Ansible host
      ansible.builtin.copy:
        content: "{{ user_info_results.stdout }}"
        dest: "/tmp/pre_checks/5.3_pre_check.{{ ansible_hostname }}.txt"
      delegate_to: localhost
