---
- name: Check if /smit.log exists
  ansible.builtin.stat:
    path: /smit.log
  register: smit_log_stat

- name: 4.1.1.1 Ensure access on /smit.log is configured
  ansible.builtin.file:
    path: /smit.log
    mode: o-rw
  when: smit_log_stat.stat.exists

- name: Check if /etc/group exists
  ansible.builtin.stat:
    path: /etc/group
  register: etc_group_stat

- name: 4.1.1.2 Ensure access on /etc/group is configured
  ansible.builtin.file:
    path: /etc/group
    owner: root
    group: security
    mode: u=rw,go=r
  when: etc_group_stat.stat.exists

- name: Check if /etc/inetd.conf exists
  ansible.builtin.stat:
    path: /etc/inetd.conf
  register: etc_inetd_conf_stat

- name: 4.1.1.3 Ensure access on /etc/inetd.conf is configured
  ansible.builtin.file:
    path: /etc/inetd.conf
    owner: root
    group: system
    mode: u=rw,go=r
  when: etc_inetd_conf_stat.stat.exists

- name: 4.1.1.3 Run trustchk on /etc/inetd.conf
  ansible.builtin.command: trustchk -u /etc/inetd.conf mode=644
  when: etc_inetd_conf_stat.stat.exists

- name: Check if /etc/motd exists
  ansible.builtin.stat:
    path: /etc/motd
  register: etc_motd_stat

- name: 4.1.1.4 Ensure access on /etc/motd is configured
  ansible.builtin.file:
    path: /etc/motd
    owner: bin
    group: bin
    mode: u=rw,go=r
  when: etc_motd_stat.stat.exists

- name: Check if /etc/passwd exists
  ansible.builtin.stat:
    path: /etc/passwd
  register: etc_passwd_stat

- name: 4.1.1.5 Ensure access on /etc/passwd is configured
  ansible.builtin.file:
    path: /etc/passwd
    owner: root
    group: security
    mode: u=rw,go=r
  when: etc_passwd_stat.stat.exists

- name: Check if /etc/mail/submit.cf exists
  ansible.builtin.stat:
    path: /etc/mail/submit.cf
  register: etc_submit_cf_stat

- name: 4.1.1.6 Ensure /etc/mail/submit.cf access is configured
  ansible.builtin.file:
    path: /etc/mail/submit.cf
    mode: u=rw,g=r,o=
  when: etc_submit_cf_stat.stat.exists

- name: Check if /etc/ssh/ssh_banner exists
  ansible.builtin.stat:
    path: /etc/ssh/ssh_banner
  register: etc_ssh_banner_stat

- name: 4.1.1.7 Ensure access to /etc/ssh/ssh_banner is configured
  ansible.builtin.file:
    path: /etc/ssh/ssh_banner
    owner: root
    group: system
    mode: u=rw,go=r
  when: etc_ssh_banner_stat.stat.exists

- name: Check if /etc/ssh/ssh_config exists
  ansible.builtin.stat:
    path: /etc/ssh/ssh_config
  register: etc_ssh_config_stat

- name: 4.1.1.8 Ensure access on /etc/ssh/ssh_config is configured
  ansible.builtin.file:
    path: /etc/ssh/ssh_config
    mode: '644'
  when: etc_ssh_config_stat.stat.exists

- name: Check if /etc/ssh/sshd_config exists
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config
  register: etc_sshd_config_stat

- name: 4.1.1.9 Ensure access on /etc/ssh/sshd_config is configured
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    mode: u=rw,go=r
  when: etc_sshd_config_stat.stat.exists

- name: Check if /var/adm/cron/cron.allow exists
  ansible.builtin.stat:
    path: /var/adm/cron/cron.allow
  register: cron_allow_stat

- name: 4.1.1.11 Ensure access on /var/adm/cron/cron.allow is configured
  ansible.builtin.file:
    path: /var/adm/cron/cron.allow
    owner: root
    group: sys
    mode: u=r,go=
  when: cron_allow_stat.stat.exists

- name: Check if /var/ct/RMstart.log exists
  ansible.builtin.stat:
    path: /var/ct/RMstart.log
  register: rmstart_log_stat

- name: 4.1.1.13 Ensure access on /var/ct/RMstart.log is configured
  ansible.builtin.file:
    path: /var/ct/RMstart.log
    mode: o-rw
  when: rmstart_log_stat.stat.exists

- name: Check if /var/tmp/dpid2.log exists
  ansible.builtin.stat:
    path: /var/tmp/dpid2.log
  register: dpid2_log_stat

- name: 4.1.1.14 Ensure access on /var/tmp/dpid2.log is configured
  ansible.builtin.file:
    path: /var/tmp/dpid2.log
    mode: o-rw
  when: dpid2_log_stat.stat.exists

- name: Check if /var/tmp/hostmibd.log exists
  ansible.builtin.stat:
    path: /var/tmp/hostmibd.log
  register: hostmibd_log_stat

- name: 4.1.1.15 Ensure access on /var/tmp/hostmibd.log is configured
  ansible.builtin.file:
    path: /var/tmp/hostmibd.log
    mode: o-rw
  when: hostmibd_log_stat.stat.exists

- name: Check if /var/tmp/snmpd.log exists
  ansible.builtin.stat:
    path: /var/tmp/snmpd.log
  register: snmpd_log_stat

- name: 4.1.1.16 Ensure access on /var/tmp/snmpd.log is configured
  ansible.builtin.file:
    path: /var/tmp/snmpd.log
    mode: o-rw
  when: snmpd_log_stat.stat.exists

- name: Final trustchk for /etc/inetd.conf
  ansible.builtin.command: trustchk -u /etc/inetd.conf mode=644
  when: etc_inetd_conf_stat.stat.exists
